# Generated by Django 4.1.1 on 2022-09-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0002_perfil_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
