# Generated by Django 4.1.1 on 2022-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0003_alter_perfil_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
