# Generated by Django 4.1.1 on 2022-09-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0004_alter_perfil_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
