# Generated by Django 4.1 on 2022-09-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weight", models.IntegerField()),
                ("reps", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
