# Generated by Django 4.1.1 on 2022-09-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="pr", name="date",),
    ]
