# Generated by Django 4.1.1 on 2022-09-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0002_remove_pr_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pr_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weight", models.CharField(max_length=100)),
                ("reps", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(name="PR",),
    ]
