# Generated by Django 4.1.1 on 2022-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0004_alter_pr_detail_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rm_detail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("weight", models.CharField(max_length=100)),
                ("reps", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
