# Generated by Django 4.1.1 on 2022-09-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0006_prbacksquat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pr_detail", options={"ordering": ("date", "name")},
        ),
    ]
