# Generated by Django 4.1.1 on 2022-09-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0009_alter_pr_detail_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pr_detail",
            name="name",
            field=models.CharField(
                choices=[
                    ("BS", "Back Squat"),
                    ("FS", "Front Squat"),
                    ("DL", "Dead Lift"),
                    ("CL", "Clean"),
                    ("SN", "Snatch"),
                ],
                default="BS",
                max_length=100,
            ),
        ),
    ]
