# Generated by Django 4.1.1 on 2022-09-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0010_alter_pr_detail_name"),
    ]

    operations = [
        migrations.DeleteModel(name="PrBackSquat",),
        migrations.AlterModelOptions(
            name="rm_detail", options={"ordering": ("name", "-date")},
        ),
        migrations.AlterField(
            model_name="rm_detail",
            name="name",
            field=models.CharField(
                choices=[
                    ("TTB", "Toes To Bar"),
                    ("PU", "Pull Up"),
                    ("CTB", "Chest To Bar"),
                    ("WB", "Wall Ball"),
                    ("SU", "Simple Under"),
                    ("DU", "Double Under"),
                    ("BR", "Burpee"),
                ],
                default="TTB",
                max_length=100,
            ),
        ),
    ]
