# Generated by Django 4.1.1 on 2022-09-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0011_delete_prbacksquat_alter_rm_detail_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rm_detail",
            name="name",
            field=models.CharField(
                choices=[
                    ("TTB", "Toes To Bar"),
                    ("PU", "Pull Up"),
                    ("CTB", "Chest To Bar"),
                    ("WB", "Wall Ball"),
                    ("SU", "Simple Under"),
                    ("DU", "Double Under"),
                    ("BR", "Burpee"),
                ],
                default="TTB",
                max_length=100,
                null=True,
            ),
        ),
    ]
