# Generated by Django 4.1.1 on 2022-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrenamiento", "0012_alter_rm_detail_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeCap_detail",
            fields=[
                ("Nombre", models.CharField(max_length=100)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[(models.CharField(max_length=100), "Nombre")],
                        default=models.CharField(max_length=100),
                        max_length=100,
                    ),
                ),
                ("time", models.CharField(max_length=100)),
                ("date", models.DateField()),
            ],
            options={"ordering": ("name", "-date"),},
        ),
    ]
